### ISSUE TITLE
Prebuilt Windows does not seem to work

### ISSUE THREAD

**Issue by mcclure** [maierfelix/chromium-ray-tracing#3]
Hello, I have been learning WebGPU and am very interested in trying out the raytrace fork. I am testing on Windows 10 with a Geforce 3070ti.

I downloaded your Windows "release" and tried the sample page https://maierfelix.github.io/chromium-ray-tracing-demo/

The window displayed plain white, and when I opened Inspector I saw these errors:

![image](https://user-images.githubusercontent.com/277318/126407512-0617d76d-c381-435f-a17a-5072224553e9.png)

The notes said to put dxcompiler and dxil "alongside" Chrome.exe. I downloaded them and placed them there, it made no difference. I tried dragging them into the "84.0.4142.0" directory but there were already files by those names in there.

Is this surprising? Do you expect the Chromium "Release" to work? Should I try building it myself?

Thanks.

**Comment by maierfelix** [comment]
You need to run chrome from the command line like this `chrome.exe --disable-gpu-sandbox`, that should fix your issue. IIRC I added a patch to fix this issue, but didn't upload the new binary.

**Comment by mcclure** [comment]
Thanks so much, it works now.

I see now that this is explained in the README. Sorry I was not paying attention :)
